language: java
jdk:
  - openjdk13

sudo: false

addons:
  apt:
    packages:
      - tree

before_install:
  - rvm install 2.2.5
  - rvm use 2.2.5
  - bin/build-jq.sh  # we want jq 1.5 features; not avail through pkg repo.

install: true  # if we don't skip install, ./gradlew assemble is invoked, but this task is not available.

before_script:
 - echo "Starting build"

script:
  - cd lab_01
  - ./gradlew build --scan -s
  
#cache:
#  bundler: true
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/
